/**
 * get-key.js — Netlify Function
 *
 * Called by success.html after Stripe checkout completes.
 * Retrieves the API key generated by stripe-webhook.js for the given session.
 *
 * Environment variables required:
 *   SUPABASE_URL        — Supabase project URL
 *   SUPABASE_ANON_KEY   — Supabase anon key
 *
 * Query parameters:
 *   session_id  — Stripe checkout session ID
 */

exports.handler = async (event) => {
  const headers = {
    "Access-Control-Allow-Origin": "*",
    "Content-Type": "application/json",
  };

  if (event.httpMethod === "OPTIONS") {
    return { statusCode: 200, headers, body: "" };
  }

  const { session_id } = event.queryStringParameters || {};

  if (!session_id) {
    return {
      statusCode: 400,
      headers,
      body: JSON.stringify({ error: "session_id required" }),
    };
  }

  // ── Option A: Supabase (recommended) ───────────────────────────────────────
  // Requires: SUPABASE_URL, SUPABASE_ANON_KEY env vars
  // stripe-webhook.js must have stored the key with checkout_session_id as lookup
  if (process.env.SUPABASE_URL && process.env.SUPABASE_ANON_KEY) {
    try {
      const { createClient } = require("@supabase/supabase-js");
      const supabase = createClient(
        process.env.SUPABASE_URL,
        process.env.SUPABASE_ANON_KEY
      );

      const { data, error } = await supabase
        .from("api_keys")
        .select("api_key")
        .eq("checkout_session_id", session_id)
        .single();

      if (error || !data) {
        return {
          statusCode: 404,
          headers,
          body: JSON.stringify({
            error: "Key not found. It may still be processing — retry in a few seconds.",
          }),
        };
      }

      return {
        statusCode: 200,
        headers,
        body: JSON.stringify({ apiKey: data.api_key }),
      };
    } catch (err) {
      console.error("[get-key] Supabase error:", err.message);
      return {
        statusCode: 500,
        headers,
        body: JSON.stringify({ error: "Key lookup failed" }),
      };
    }
  }

  // ── Option B: No storage configured ────────────────────────────────────────
  // Return a clear message so the developer knows what to wire up
  return {
    statusCode: 503,
    headers,
    body: JSON.stringify({
      error:
        "Key storage not configured. Set SUPABASE_URL and SUPABASE_ANON_KEY " +
        "in Netlify environment variables, and ensure stripe-webhook.js is " +
        "storing keys to the api_keys table.",
    }),
  };
};
