"""
Shared test constants for aiglos.

Centralized here so version bumps, rule additions, and campaign additions
only require a single-file update instead of touching 30+ test files.
"""

EXPECTED_VERSION = "0.25.17"

EXPECTED_RULE_COUNT = 44

EXPECTED_CAMPAIGN_COUNT = 25

EXPECTED_CAMPAIGN_NAMES = {
    "RECON_SWEEP",
    "CREDENTIAL_ACCUMULATE",
    "EXFIL_SETUP",
    "PERSISTENCE_CHAIN",
    "LATERAL_PREP",
    "AGENTDEF_CHAIN",
    "MEMORY_PERSISTENCE_CHAIN",
    "REWARD_MANIPULATION",
    "EXTERNAL_INSTRUCTION_CHANNEL",
    "REPEATED_INJECTION_ATTEMPT",
    "SKILL_CHAIN",
    "SANDBOX_ESCAPE_ATTEMPT",
    "SANDBOX_CONFIRMED_ESCAPE",
    "GAAS_TAKEOVER",
    "INFERENCE_HIJACK_CHAIN",
    "RAG_POISON_CHAIN",
    "MULTI_AGENT_IMPERSONATION",
    "CAPABILITY_EXPLOIT_CHAIN",
    "SUPERPOWERS_PLAN_HIJACK",
    "GIGABRAIN_MEMORY_POISON",
    "NEMOCLAW_POLICY_HIJACK",
    "REPO_TAKEOVER_CHAIN",
    "METACOGNITIVE_POISON_CHAIN",
    "IP_CIRCUMVENTION_CHAIN",
    "MEMORY_ENTROPY_ATTACK",
}

EXPECTED_KNOWN_AGENT_COUNT = 17
