"""
config.py — Aiglos guard configuration for my-agent

Generated by aiglos launch v0.25.3
This file is the security runtime for your agent. Import it before any tool calls.

Usage:
    from .aiglos.config import guard, session
    result = guard.before_tool_call("tool_name", args)
    if result.verdict == "BLOCK":
        raise RuntimeError(f"Blocked: {result.reason}")
"""

import aiglos
from aiglos.integrations.openclaw import OpenClawGuard
from aiglos.integrations.agent_phase import AgentPhase
from aiglos.integrations.gigabrain import gigabrain_autodetect

# ── Guard configuration ───────────────────────────────────────────────────────

guard = OpenClawGuard(
    agent_name = "my-agent",
    policy     = "enterprise",
    log_path   = ".aiglos/session.aiglos",
    sandbox_context   = False,
    intercept_http    = True,
    intercept_subprocess = True,
)

# ── Declare expected sub-agents ───────────────────────────────────────────────

guard.declare_subagent(
    "ceo-agent",
    tools=["filesystem", "web_search", "git.push"],
    scope_files=["main"],
    model="claude-opus-4-6",
    hard_bans=["merge_without_review", "fabricate_data"],
)
guard.declare_subagent(
    "assistant-agent",
    tools=["filesystem", "web_search", "git.push"],
    scope_files=["branches/", "src/"],
    model="moonshot-v1",
    hard_bans=["push_to_main", "fabricate_data"],
)


# ── Persistent memory protection (T79) ───────────────────────────────────────
# learnings.md is a cross-session persistent file — protect its write path
gigabrain_autodetect(guard)   # also protects ~/.gigabrain/ if Gigabrain is installed

# Register learnings.md as a protected persistent path
from aiglos.integrations.gigabrain import declare_memory_backend
declare_memory_backend(guard, backend="generic",
                       db_path=".aiglos/learnings.md")

# ── Heartbeat awareness ───────────────────────────────────────────────────────
# T67 HEARTBEAT_SILENCE monitors the 30-minute heartbeat cadence
# Call guard.on_heartbeat() at the start of each heartbeat cycle

# ── Allowed hosts (from tools.md) ────────────────────────────────────────────
ALLOWED_HOSTS = [
    "api.github.com",
    "api.notion.com",
    "api.twitter.com",
    "api.x.com",
    "github.com",
    "www.googleapis.com"
]

# ── Session lifecycle ─────────────────────────────────────────────────────────

def close_session():
    """Close the session and write the signed artifact. Call at agent shutdown."""
    artifact = guard.close_session()
    print(f"[Aiglos] Session closed — {artifact.total_calls} calls, "
          f"{artifact.blocked_calls} blocked. Artifact: .aiglos/session.aiglos")
    return artifact


# ── GOVBENCH baseline ─────────────────────────────────────────────────────────
# Run once after setup to establish day-one baseline grade:
#   python -c "import aiglos; aiglos.benchmark_run()"
